# Generated by Django 6.0 on 2025-12-15 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramaFormacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('nivel', models.CharField(choices=[('Técnico', 'Técnico'), ('Tecnólogo', 'Tecnólogo'), ('Auxiliar', 'Auxiliar')], max_length=50)),
                ('duracion', models.SmallIntegerField()),
                ('modalidad', models.CharField(max_length=50)),
            ],
        ),
    ]
