
TIPO_DOCUMENTO_CC = "CC"
TIPO_DOCUMENTO_TI = "TI"
TIPO_DOCUMENTO_CE = "CE"

TIPO_DOCUMENTO_CHOICES = [
    (TIPO_DOCUMENTO_CC, "Cédula de ciudadanía"),
    (TIPO_DOCUMENTO_TI, "Tarjeta de identidad"),
    (TIPO_DOCUMENTO_CE, "Cédula de extranjería"),
]

ROL_APRENDIZ = "APRENDIZ"
ROL_INSTRUCTOR = "INSTRUCTOR"
ROL_ADMIN = "ADMIN"

ROL_CHOICES = [
    (ROL_APRENDIZ, "Aprendiz"),
    (ROL_INSTRUCTOR, "Instructor"),
    (ROL_ADMIN, "Administrador"),
]

ESTADO_ACTIVO = "ACTIVO"
ESTADO_INACTIVO = "INACTIVO"
ESTADO_SUSPENDIDO = "SUSPENDIDO"

ESTADO_CHOICES = [
    (ESTADO_ACTIVO, "Activo"),
    (ESTADO_INACTIVO, "Inactivo"),
    (ESTADO_SUSPENDIDO, "Suspendido"),
]
