# Generated by Django 5.2.9 on 2025-12-16 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appAvanser', '0002_rol_usuario_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignacioninstructortrimestre',
            name='es_lider_trimestre',
        ),
    ]
