# Generated by Django 5.2.9 on 2025-12-16 21:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAvanser', '0004_encuesta_preguntaencuesta_respuestaencuesta'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaracterizacionResumen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('puntaje_global', models.FloatField(blank=True, null=True)),
                ('nivel_riesgo', models.CharField(blank=True, choices=[('Bajo', 'Bajo'), ('Medio', 'Medio'), ('Alto', 'Alto'), ('Crítico', 'Crítico')], max_length=10, null=True)),
                ('detalle_dimensiones', models.JSONField(blank=True, default=dict)),
                ('aprendiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caracterizaciones', to=settings.AUTH_USER_MODEL)),
                ('ficha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caracterizaciones', to='appAvanser.ficha')),
                ('trimestre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caracterizaciones', to='appAvanser.trimestre')),
            ],
        ),
        migrations.CreateModel(
            name='Riesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('nivel', models.CharField(choices=[('Bajo', 'Bajo'), ('Medio', 'Medio'), ('Alto', 'Alto'), ('Crítico', 'Crítico')], max_length=10)),
                ('generado_por', models.CharField(choices=[('SISTEMA', 'Sistema'), ('INSTRUCTOR', 'Instructor'), ('BIENESTAR', 'Bienestar')], max_length=20)),
                ('aprendiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riesgos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
