# Generated by Django 6.0 on 2025-12-15 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aprendiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ficha', models.CharField(max_length=10)),
                ('programa', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Convocatoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('cupos_totales', models.IntegerField()),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('estado', models.CharField(choices=[('BORRADOR', 'BORRADOR'), ('ACTIVA', 'ACTIVA'), ('INACTIVA', 'INACTIVA'), ('CERRADA', 'CERRADA'), ('FINALIZADA', 'FINALIZADA')], max_length=50)),
                ('documento', models.FileField(blank=True, null=True, upload_to='documentos/')),
            ],
        ),
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ProgramaFormacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('nivel', models.CharField(choices=[('Técnico', 'Técnico'), ('Tecnólogo', 'Tecnólogo'), ('Auxiliar', 'Auxiliar')], max_length=50)),
                ('duracion', models.SmallIntegerField()),
                ('modalidad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoCaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoConvocatoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('tipo_documento', models.CharField(choices=[('CC', 'CC'), ('TI', 'TI'), ('PASAPORTE', 'PASAPORTE')], max_length=50)),
                ('documento', models.CharField(max_length=15, unique=True)),
                ('correo', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('INACTIVO', 'INACTIVO')], max_length=50)),
                ('password', models.CharField(max_length=60)),
                ('rol', models.CharField(choices=[('Funcionario', 'Funcionario'), ('Instructor', 'Instructor'), ('Aprendiz', 'Aprendiz')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_postulacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('APROBADO', 'APROBADO'), ('RECHAZADO', 'RECHAZADO')], max_length=50)),
                ('aprendiz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appAvanser.aprendiz')),
                ('convocatoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appAvanser.convocatoria')),
            ],
        ),
        migrations.CreateModel(
            name='PreguntaEncuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('tipo', models.CharField(choices=[('texto', 'texto'), ('opción', 'opción'), ('multiple', 'multiple'), ('escala', 'escala')], max_length=50)),
                ('dimension', models.CharField(max_length=50)),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appAvanser.encuesta')),
            ],
        ),
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('jornada', models.CharField(choices=[('Mañana', 'Mañana'), ('Tarde', 'Tarde'), ('Noche', 'Noche')], max_length=50)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appAvanser.programaformacion')),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaEncuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.TextField()),
                ('valor_numerico', models.FloatField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('aprendiz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appAvanser.aprendiz')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appAvanser.preguntaencuesta')),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoPostulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.TextField()),
                ('fecha_resultado', models.DateTimeField(auto_now_add=True)),
                ('estado_final', models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('APROBADO', 'APROBADO'), ('RECHAZADO', 'RECHAZADO')], max_length=50)),
                ('postulacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appAvanser.postulacion')),
            ],
        ),
        migrations.CreateModel(
            name='Riesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('BAJO', 'BAJO'), ('MEDIO', 'MEDIO'), ('ALTO', 'ALTO')], max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('generado_por', models.CharField(choices=[('SISTEMA', 'SISTEMA'), ('INSTRUCTOR', 'INSTRUCTIR'), ('BIENESTAR', 'BIENESTAR')], max_length=50)),
                ('aprendiz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appAvanser.aprendiz')),
            ],
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appAvanser.tipoconvocatoria'),
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('tipo', models.CharField(choices=[('ENCUESTA', 'ENCUESTA'), ('CASO', 'CASO'), ('AYUDA', 'AYUDA'), ('SISTEMA', 'SISTEMA')], max_length=50)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('ENVIADA', 'ENVIADA'), ('LEIDA', 'LEIDA')], max_length=50)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appAvanser.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=50)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appAvanser.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='aprendiz',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appAvanser.usuario'),
        ),
    ]
